### ISSUE TITLE
ROM Contents

### ISSUE THREAD

**Issue by ryaneroth** [eduardocasino/kim-1-dual-6532-adapter#1]
Is there code available for the ROMs content?

**Comment by eduardocasino** [comment]
Hi Ryan,

You can get the ROM contents from Hans Otten's site:

http://retro.hansotten.nl/6502-sbc/kim-1-manuals-and-software/kim_1-roms/

There are two sets available: One that uses $00 as filler bytes and another that uses $FF. Both work equally well, but the one with $00 is what the original KIM-1 has. To program the EPROM:

1. Download "6530-002 fillerbyte00.bin" and "6530-003 fillerbyte00.bin" from Hans Otten's site (replace 00 with ff if you wish)
"6530-003 fillerbyte00.bin" has the ROM contents from $1800 to $1BFF and
"6530-002 fillerbyte00.bin" from $1C00 to $1FFF

3. Concat both files:
`$ cat "6530-003 fillerbyte00.bin" "6530-002 fillerbyte00.bin" > KIM-1-ROM.bin`

4. Program the EPROM with the resulting file starting at address $1800

I'm adding this instructions to the README.

Cheers,
Eduardo
